# Generated by Django 3.2.6 on 2021-09-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('trabajador_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cedula', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('numero_celular', models.CharField(max_length=15)),
                ('contrasena', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Trabajadores',
            },
        ),
    ]
