# Generated by Django 3.2.6 on 2021-09-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_nit', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Clientes',
            },
        ),
        migrations.AddField(
            model_name='trabajador',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
