# Generated by Django 3.2.6 on 2021-09-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmAPI', '0002_auto_20210924_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('obra_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=1)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
            options={
                'db_table': 'Obras',
            },
        ),
    ]
