# Generated by Django 3.2.6 on 2021-09-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmAPI', '0004_rename_estado_obra_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='latitud',
            field=models.FloatField(unique=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='longitud',
            field=models.FloatField(unique=True),
        ),
    ]
