# Generated by Django 3.2.6 on 2021-09-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmAPI', '0005_auto_20210929_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='latitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='obra',
            name='longitud',
            field=models.FloatField(),
        ),
    ]
