# Generated by Django 3.2.6 on 2021-10-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmAPI', '0006_auto_20210929_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='clientes_participantes',
            field=models.ManyToManyField(to='cpmAPI.Cliente'),
        ),
        migrations.AddField(
            model_name='obra',
            name='trabajadores_participantes',
            field=models.ManyToManyField(to='cpmAPI.Trabajador'),
        ),
    ]
