# Generated by Django 3.2.6 on 2021-10-12 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpmAPI', '0007_auto_20211001_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='clientes_participantes',
        ),
        migrations.AddField(
            model_name='obra',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cpmAPI.cliente'),
        ),
    ]
