# Generated by Django 3.2.6 on 2021-10-12 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpmAPI', '0008_auto_20211011_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpmAPI.cliente'),
        ),
    ]
