# Generated by Django 3.2.6 on 2021-10-13 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpmAPI', '0009_alter_obra_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('avance_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=2000)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpmAPI.obra')),
            ],
            options={
                'db_table': 'Avances',
            },
        ),
    ]
