# Generated by Django 3.2.6 on 2021-10-13 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpmAPI', '0010_avance_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpmAPI.material')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpmAPI.obra')),
            ],
            options={
                'db_table': 'Obras_Materiales',
            },
        ),
    ]
