# Generated by Django 3.2.6 on 2021-10-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmAPI', '0011_inventarioobra'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='tipo',
            field=models.IntegerField(default=1),
        ),
    ]
