# Generated by Django 3.2.6 on 2021-10-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmAPI', '0012_avance_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='obra_participante',
            field=models.IntegerField(default=0),
        ),
    ]
