# Generated by Django 3.2.6 on 2021-10-14 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cpmAPI', '0014_inventarioobra_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='fase',
            field=models.CharField(default='3', max_length=1),
        ),
        migrations.AddField(
            model_name='avance',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
