# Generated by Django 3.2.6 on 2021-10-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmAPI', '0015_auto_20211014_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
