# Generated by Django 3.2.6 on 2021-10-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmAPI', '0016_avance_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='trabajador',
            field=models.CharField(default='', max_length=100),
        ),
    ]
